# Generated by Django 4.1.4 on 2023-03-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_color_product_remove_color_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
