# Generated by Django 4.1.4 on 2023-03-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_colorcombination_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorcombination',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_combinations', to='app.color'),
        ),
    ]
