# Generated by Django 4.1.4 on 2023-03-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_colorcombination_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(default='cash on delivery', max_length=50),
        ),
    ]
