# Generated by Django 4.1.4 on 2023-03-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_orderplaced_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
    ]
