# Generated by Django 4.1.4 on 2023-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_orderplaced_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
