# Generated by Django 4.1.4 on 2023-03-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_orderplaced_discount_orderplaced_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
